### ISSUE TITLE
Выбор движка/фрейворка для проекта

### ISSUE THREAD

**Issue by RomanKorolev** [narod-fl/narod_freelance#1]
Задача обсудить существующие **движки/фреймворки** и выбрать оптимальный для его использования в проекте

Это одна из **основных задач**, лучше потратить месяц сейчас на обсуждение и выбор фреймворка, чем ковыряться и мучиться потом все время и только когда проект разрастется придти к выводу что выбор был неверный.

По языкам программирования есть варианты: **php, ruby, perl, python, asp**.
Я их привел в порядке предпочтения и я склоняюсь скорее **рнр**.

Каковы требования в движку/фреймворку:
- высокая производительность/низкая нагрузка на сервер.
- ?

**Comment by RomanKorolev** [comment]
На текущий момент есть предложение использовать **wordpress/joomla**, в принципе если заморочиться то можно расширить статья==проект, теги сойдут за специальности, автор сойдет за заказчика :)

Есть другой вариант **Laravel** или какой-нибудь аналог

**Comment by RomanKorolev** [comment]
поступило предложение использовать [**готовый движок**](https://cmsworks.ru/apps/freelance2) на 

> Сборка фриланс-биржи на базе **Cotonti Siena**. С помощью данной сборки можно организовать любую электронную биржу. Функционал биржи предоставляет гибкие возможности для эксплуатации и дальнейшей разработки.

**Comment by RomanKorolev** [comment]
еще варианты: symphony, smarty (это просто шаблонизатор)

**Comment by RomanKorolev** [comment]
еще вариант [CodeIgniter](www.codeigniter.com/) opensource фрейворк так же выложен в гит :)
последняя версия 3.0+

**Comment by RomanKorolev** [comment]
остановился на последнем

**Comment by mathprocessing** [comment]
если безопасность важна, еще можно свой движок написать.

**Comment by RomanKorolev** [comment]
дык вопрос закрыт, проект уже запущен на самописном движке http://narod-fl.ru/
